### ISSUE TITLE
git lfs pull fails

### ISSUE THREAD

**Issue by PanAeon** [markol/machines#9]
```batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
Failed to fetch some objects from 'https://github.com/markol/machines.git/info/lfs'
```
If the data files are on original disks could you document which files are needed?

**Comment by Kaffeine** [comment]
The issue is identical to https://github.com/markol/machines/issues/8, though your question is something new. I've attached a zip with cloned repository and steps to verify the copy; check the comments in #8 for details.

The files in LFS are precompied libraries for win32 & win64 (e.g. https://github.com/markol/machines/tree/master/windows/lib64).
The files are in the repository history and now there is no other way than rewriting the repository without LFS.

I did such rewrite in a fork, and extracted the libraries to own repository. Namely:
- https://github.com/WiredForWar/machines/tree/upstream/as-is is identical to this repo, except for the redone commits
- https://github.com/WiredForWar/machines-packager/tree/dev/mingw64 contains win64 libraries (hm, it seems that I didn't care for win32 because there was no demand from users)

You may be interested in community fork with improved UX and modernized code: https://github.com/WiredForWar/machines
Also consider joining our Discord server (created by @markol): https://discord.gg/nXBdB983hn

**Comment by PanAeon** [comment]
@Kaffeine Hi, thanks, `WiredForWar/machines` had built flawlessly. I think the **REAME.md** needs to be updated, as it explicitly asks to use `git-lfs` which is confusing.
